name: NPM Package Publish

on:
  release:
    types: [created]

jobs:
  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.yarnjs.org/
      - run: yarn install
      - run: yarn run lint
      - run: yarn test
      - run: yarn run build
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.yarn_token}}
