name: Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn install
      - run: yarn run lint
      - run: yarn run test:coverage
        env:
          COVERALLS_REPO_TOKEN: ${{secrets.coveralls_repo_token}}
          CONTINUOUS_INTEGRATION: true
